events { worker_connections 1024; }

http {
  server {
    listen 80;
    server_name mshl.in meshalive.in;

    location / {
      rewrite ^/(.+)$ /r/$1 break;
      proxy_pass http://api:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header CF-IPCountry $http_cf_ipcountry;
    }
  }

  server {
    listen 80;
    server_name api.meshalive.com api.meshalive.in localhost;

    location / {
      proxy_pass http://api:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name app.meshalive.com meshalive.com _;

    location / {
      proxy_pass http://web:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
