// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getClicksByDay = `-- name: GetClicksByDay :many
SELECT DATE(c.clicked_at) AS day, COUNT(*) AS clicks
FROM clicks c
JOIN links l ON l.id = c.link_id
WHERE l.workspace_id = $1 AND l.archived = false
  AND c.clicked_at >= NOW() - ($2::int || ' days')::interval
GROUP BY day
ORDER BY day
`

type GetClicksByDayParams struct {
	WorkspaceID uuid.UUID
	Column2     int32
}

type GetClicksByDayRow struct {
	Day    time.Time
	Clicks int64
}

func (q *Queries) GetClicksByDay(ctx context.Context, arg GetClicksByDayParams) ([]GetClicksByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getClicksByDay, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClicksByDayRow
	for rows.Next() {
		var i GetClicksByDayRow
		if err := rows.Scan(&i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkClicksByDay = `-- name: GetLinkClicksByDay :many
SELECT DATE(clicked_at) AS day, COUNT(*) AS clicks
FROM clicks
WHERE link_id = $1
  AND clicked_at >= NOW() - ($2::int || ' days')::interval
GROUP BY day
ORDER BY day
`

type GetLinkClicksByDayParams struct {
	LinkID  uuid.UUID
	Column2 int32
}

type GetLinkClicksByDayRow struct {
	Day    time.Time
	Clicks int64
}

func (q *Queries) GetLinkClicksByDay(ctx context.Context, arg GetLinkClicksByDayParams) ([]GetLinkClicksByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkClicksByDay, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkClicksByDayRow
	for rows.Next() {
		var i GetLinkClicksByDayRow
		if err := rows.Scan(&i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkTopCountries = `-- name: GetLinkTopCountries :many
SELECT COALESCE(country, 'XX') AS country, COUNT(*) AS clicks
FROM clicks
WHERE link_id = $1
  AND clicked_at >= NOW() - ($2::int || ' days')::interval
GROUP BY country
ORDER BY clicks DESC
LIMIT 10
`

type GetLinkTopCountriesParams struct {
	LinkID  uuid.UUID
	Column2 int32
}

type GetLinkTopCountriesRow struct {
	Country string
	Clicks  int64
}

func (q *Queries) GetLinkTopCountries(ctx context.Context, arg GetLinkTopCountriesParams) ([]GetLinkTopCountriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkTopCountries, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkTopCountriesRow
	for rows.Next() {
		var i GetLinkTopCountriesRow
		if err := rows.Scan(&i.Country, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkTopDevices = `-- name: GetLinkTopDevices :many
SELECT COALESCE(device, 'unknown') AS device, COUNT(*) AS clicks
FROM clicks
WHERE link_id = $1
  AND clicked_at >= NOW() - ($2::int || ' days')::interval
GROUP BY device
ORDER BY clicks DESC
LIMIT 5
`

type GetLinkTopDevicesParams struct {
	LinkID  uuid.UUID
	Column2 int32
}

type GetLinkTopDevicesRow struct {
	Device string
	Clicks int64
}

func (q *Queries) GetLinkTopDevices(ctx context.Context, arg GetLinkTopDevicesParams) ([]GetLinkTopDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkTopDevices, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkTopDevicesRow
	for rows.Next() {
		var i GetLinkTopDevicesRow
		if err := rows.Scan(&i.Device, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkTotalClicks = `-- name: GetLinkTotalClicks :one
SELECT COUNT(*) AS clicks FROM clicks WHERE link_id = $1
`

func (q *Queries) GetLinkTotalClicks(ctx context.Context, linkID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLinkTotalClicks, linkID)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}

const getTopCountries = `-- name: GetTopCountries :many
SELECT COALESCE(c.country, 'XX') AS country, COUNT(*) AS clicks
FROM clicks c
JOIN links l ON l.id = c.link_id
WHERE l.workspace_id = $1 AND l.archived = false
  AND c.clicked_at >= NOW() - ($2::int || ' days')::interval
GROUP BY country
ORDER BY clicks DESC
LIMIT 10
`

type GetTopCountriesParams struct {
	WorkspaceID uuid.UUID
	Column2     int32
}

type GetTopCountriesRow struct {
	Country string
	Clicks  int64
}

func (q *Queries) GetTopCountries(ctx context.Context, arg GetTopCountriesParams) ([]GetTopCountriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopCountries, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCountriesRow
	for rows.Next() {
		var i GetTopCountriesRow
		if err := rows.Scan(&i.Country, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopDevices = `-- name: GetTopDevices :many
SELECT COALESCE(c.device, 'unknown') AS device, COUNT(*) AS clicks
FROM clicks c
JOIN links l ON l.id = c.link_id
WHERE l.workspace_id = $1 AND l.archived = false
  AND c.clicked_at >= NOW() - ($2::int || ' days')::interval
GROUP BY device
ORDER BY clicks DESC
LIMIT 5
`

type GetTopDevicesParams struct {
	WorkspaceID uuid.UUID
	Column2     int32
}

type GetTopDevicesRow struct {
	Device string
	Clicks int64
}

func (q *Queries) GetTopDevices(ctx context.Context, arg GetTopDevicesParams) ([]GetTopDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopDevices, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDevicesRow
	for rows.Next() {
		var i GetTopDevicesRow
		if err := rows.Scan(&i.Device, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopLinks = `-- name: GetTopLinks :many
SELECT l.id, l.slug, l.title, l.destination, COUNT(c.id) AS clicks
FROM links l
LEFT JOIN clicks c ON c.link_id = l.id
WHERE l.workspace_id = $1 AND l.archived = false
GROUP BY l.id
ORDER BY clicks DESC
LIMIT 10
`

type GetTopLinksRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Destination string
	Clicks      int64
}

func (q *Queries) GetTopLinks(ctx context.Context, workspaceID uuid.UUID) ([]GetTopLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopLinks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopLinksRow
	for rows.Next() {
		var i GetTopLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Destination,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceAnalyticsSummary = `-- name: GetWorkspaceAnalyticsSummary :one
SELECT
  COUNT(DISTINCT l.id)                                                          AS total_links,
  COUNT(c.id)                                                                   AS total_clicks,
  COUNT(c.id) FILTER (WHERE c.clicked_at >= CURRENT_DATE)                      AS clicks_today,
  COUNT(c.id) FILTER (WHERE c.clicked_at >= CURRENT_DATE - INTERVAL '7 days') AS clicks_week
FROM links l
LEFT JOIN clicks c ON c.link_id = l.id
WHERE l.workspace_id = $1 AND l.archived = false
`

type GetWorkspaceAnalyticsSummaryRow struct {
	TotalLinks  int64
	TotalClicks int64
	ClicksToday int64
	ClicksWeek  int64
}

func (q *Queries) GetWorkspaceAnalyticsSummary(ctx context.Context, workspaceID uuid.UUID) (GetWorkspaceAnalyticsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceAnalyticsSummary, workspaceID)
	var i GetWorkspaceAnalyticsSummaryRow
	err := row.Scan(
		&i.TotalLinks,
		&i.TotalClicks,
		&i.ClicksToday,
		&i.ClicksWeek,
	)
	return i, err
}

const getWorkspaceLinkIDs = `-- name: GetWorkspaceLinkIDs :many
SELECT id FROM links WHERE workspace_id = $1 AND archived = false
`

func (q *Queries) GetWorkspaceLinkIDs(ctx context.Context, workspaceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceLinkIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
