// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clicks.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertClick = `-- name: InsertClick :exec
INSERT INTO clicks (link_id, country, device, browser, referrer)
VALUES ($1, $2, $3, $4, $5)
`

type InsertClickParams struct {
	LinkID   uuid.UUID
	Country  sql.NullString
	Device   sql.NullString
	Browser  sql.NullString
	Referrer sql.NullString
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.ExecContext(ctx, insertClick,
		arg.LinkID,
		arg.Country,
		arg.Device,
		arg.Browser,
		arg.Referrer,
	)
	return err
}
