// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (workspace_id, hostname, status)
VALUES ($1, $2, 'pending')
RETURNING id, hostname, is_primary, status, verified_at
`

type CreateDomainParams struct {
	WorkspaceID uuid.UUID
	Hostname    string
}

type CreateDomainRow struct {
	ID         uuid.UUID
	Hostname   string
	IsPrimary  bool
	Status     string
	VerifiedAt sql.NullTime
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (CreateDomainRow, error) {
	row := q.db.QueryRowContext(ctx, createDomain, arg.WorkspaceID, arg.Hostname)
	var i CreateDomainRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.VerifiedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = $1 AND workspace_id = $2
`

type DeleteDomainParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, arg.ID, arg.WorkspaceID)
	return err
}

const listDomains = `-- name: ListDomains :many
SELECT id, hostname, is_primary, status, verified_at
FROM domains
WHERE workspace_id = $1
ORDER BY id
`

type ListDomainsRow struct {
	ID         uuid.UUID
	Hostname   string
	IsPrimary  bool
	Status     string
	VerifiedAt sql.NullTime
}

func (q *Queries) ListDomains(ctx context.Context, workspaceID uuid.UUID) ([]ListDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDomains, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDomainsRow
	for rows.Next() {
		var i ListDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IsPrimary,
			&i.Status,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
