// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_crud.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countLinks = `-- name: CountLinks :one
SELECT COUNT(*) FROM links
WHERE workspace_id = $1
  AND archived = $2
  AND ($3 = '' OR destination ILIKE '%' || $3 || '%' OR title ILIKE '%' || $3 || '%')
  AND ($4 = '' OR $4::text = ANY(tags))
`

type CountLinksParams struct {
	WorkspaceID uuid.UUID
	Archived    bool
	Column3     interface{}
	Column4     interface{}
}

func (q *Queries) CountLinks(ctx context.Context, arg CountLinksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks,
		arg.WorkspaceID,
		arg.Archived,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (workspace_id, domain_id, slug, destination, title, tags, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, domain_id, slug, destination, title, tags, archived, expires_at, click_limit, created_at
`

type CreateLinkParams struct {
	WorkspaceID uuid.UUID
	DomainID    uuid.UUID
	Slug        string
	Destination string
	Title       string
	Tags        []string
	CreatedBy   uuid.NullUUID
}

type CreateLinkRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DomainID    uuid.UUID
	Slug        string
	Destination string
	Title       string
	Tags        []string
	Archived    bool
	ExpiresAt   sql.NullTime
	ClickLimit  sql.NullInt32
	CreatedAt   time.Time
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.WorkspaceID,
		arg.DomainID,
		arg.Slug,
		arg.Destination,
		arg.Title,
		pq.Array(arg.Tags),
		arg.CreatedBy,
	)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.Slug,
		&i.Destination,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Archived,
		&i.ExpiresAt,
		&i.ClickLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByWorkspace = `-- name: GetDomainByWorkspace :one
SELECT id, hostname FROM domains
WHERE workspace_id = $1 AND status = 'active'
ORDER BY is_primary DESC
LIMIT 1
`

type GetDomainByWorkspaceRow struct {
	ID       uuid.UUID
	Hostname string
}

func (q *Queries) GetDomainByWorkspace(ctx context.Context, workspaceID uuid.UUID) (GetDomainByWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainByWorkspace, workspaceID)
	var i GetDomainByWorkspaceRow
	err := row.Scan(&i.ID, &i.Hostname)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, workspace_id, domain_id, slug, destination, title, tags, archived, expires_at, click_limit, created_at
FROM links WHERE id = $1 AND workspace_id = $2
`

type GetLinkByIDParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type GetLinkByIDRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DomainID    uuid.UUID
	Slug        string
	Destination string
	Title       string
	Tags        []string
	Archived    bool
	ExpiresAt   sql.NullTime
	ClickLimit  sql.NullInt32
	CreatedAt   time.Time
}

func (q *Queries) GetLinkByID(ctx context.Context, arg GetLinkByIDParams) (GetLinkByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, arg.ID, arg.WorkspaceID)
	var i GetLinkByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.Slug,
		&i.Destination,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Archived,
		&i.ExpiresAt,
		&i.ClickLimit,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, slug, destination, title, tags, archived, expires_at, click_limit, created_at, domain_id
FROM links
WHERE workspace_id = $1
  AND archived = $2
  AND ($3 = '' OR destination ILIKE '%' || $3 || '%' OR title ILIKE '%' || $3 || '%')
  AND ($4 = '' OR $4::text = ANY(tags))
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListLinksParams struct {
	WorkspaceID uuid.UUID
	Archived    bool
	Column3     interface{}
	Column4     interface{}
	Limit       int32
	Offset      int32
}

type ListLinksRow struct {
	ID          uuid.UUID
	Slug        string
	Destination string
	Title       string
	Tags        []string
	Archived    bool
	ExpiresAt   sql.NullTime
	ClickLimit  sql.NullInt32
	CreatedAt   time.Time
	DomainID    uuid.UUID
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]ListLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinks,
		arg.WorkspaceID,
		arg.Archived,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksRow
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Destination,
			&i.Title,
			pq.Array(&i.Tags),
			&i.Archived,
			&i.ExpiresAt,
			&i.ClickLimit,
			&i.CreatedAt,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLink = `-- name: SoftDeleteLink :exec
UPDATE links SET archived = true WHERE id = $1 AND workspace_id = $2
`

type SoftDeleteLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteLink, arg.ID, arg.WorkspaceID)
	return err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links SET
  destination = $3,
  title       = $4,
  tags        = $5,
  expires_at  = $6,
  click_limit = $7,
  archived    = $8
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, domain_id, slug, destination, title, tags, archived, expires_at, click_limit, created_at
`

type UpdateLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Destination string
	Title       string
	Tags        []string
	ExpiresAt   sql.NullTime
	ClickLimit  sql.NullInt32
	Archived    bool
}

type UpdateLinkRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DomainID    uuid.UUID
	Slug        string
	Destination string
	Title       string
	Tags        []string
	Archived    bool
	ExpiresAt   sql.NullTime
	ClickLimit  sql.NullInt32
	CreatedAt   time.Time
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error) {
	row := q.db.QueryRowContext(ctx, updateLink,
		arg.ID,
		arg.WorkspaceID,
		arg.Destination,
		arg.Title,
		pq.Array(arg.Tags),
		arg.ExpiresAt,
		arg.ClickLimit,
		arg.Archived,
	)
	var i UpdateLinkRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.Slug,
		&i.Destination,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Archived,
		&i.ExpiresAt,
		&i.ClickLimit,
		&i.CreatedAt,
	)
	return i, err
}
