// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: links.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getDomainByHostname = `-- name: GetDomainByHostname :one
SELECT id FROM domains
WHERE hostname = $1 AND status = 'active'
`

func (q *Queries) GetDomainByHostname(ctx context.Context, hostname string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getDomainByHostname, hostname)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLinkForRedirect = `-- name: GetLinkForRedirect :one
SELECT id, destination FROM links
WHERE domain_id = $1
  AND slug = $2
  AND archived = false
  AND (expires_at IS NULL OR expires_at > NOW())
  AND (click_limit IS NULL OR
       (SELECT COUNT(*) FROM clicks WHERE link_id = links.id) < click_limit)
LIMIT 1
`

type GetLinkForRedirectParams struct {
	DomainID uuid.UUID
	Slug     string
}

type GetLinkForRedirectRow struct {
	ID          uuid.UUID
	Destination string
}

func (q *Queries) GetLinkForRedirect(ctx context.Context, arg GetLinkForRedirectParams) (GetLinkForRedirectRow, error) {
	row := q.db.QueryRowContext(ctx, getLinkForRedirect, arg.DomainID, arg.Slug)
	var i GetLinkForRedirectRow
	err := row.Scan(&i.ID, &i.Destination)
	return i, err
}

const listActiveDomains = `-- name: ListActiveDomains :many
SELECT id, hostname FROM domains WHERE status = 'active'
`

type ListActiveDomainsRow struct {
	ID       uuid.UUID
	Hostname string
}

func (q *Queries) ListActiveDomains(ctx context.Context) ([]ListActiveDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDomainsRow
	for rows.Next() {
		var i ListActiveDomainsRow
		if err := rows.Scan(&i.ID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
