// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiToken struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	TokenHash   string
	Prefix      string
	LastUsedAt  sql.NullTime
	CreatedAt   time.Time
}

type Click struct {
	ID        int64
	LinkID    uuid.UUID
	ClickedAt time.Time
	Country   sql.NullString
	Device    sql.NullString
	Browser   sql.NullString
	Referrer  sql.NullString
}

type Domain struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Hostname    string
	IsPrimary   bool
	Status      string
	SslIssued   bool
	VerifiedAt  sql.NullTime
}

type Link struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DomainID    uuid.UUID
	Slug        string
	Destination string
	Title       string
	Tags        []string
	Archived    bool
	ExpiresAt   sql.NullTime
	ClickLimit  sql.NullInt32
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash sql.NullString
	AvatarUrl    sql.NullString
	CreatedAt    time.Time
	LastLogin    sql.NullTime
}

type Workspace struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	Plan         string
	BillingEmail sql.NullString
	Gstin        sql.NullString
	Currency     string
	CreatedAt    time.Time
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	JoinedAt    time.Time
}
