// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (workspace_id, name, token_hash, prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, name, prefix, created_at
`

type CreateAPITokenParams struct {
	WorkspaceID uuid.UUID
	Name        string
	TokenHash   string
	Prefix      string
}

type CreateAPITokenRow struct {
	ID        uuid.UUID
	Name      string
	Prefix    string
	CreatedAt time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1 AND workspace_id = $2
`

type DeleteAPITokenParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.WorkspaceID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, workspace_id FROM api_tokens WHERE token_hash = $1
`

type GetAPITokenByHashRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(&i.ID, &i.WorkspaceID)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, prefix, last_used_at, created_at
FROM api_tokens
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListAPITokensRow struct {
	ID         uuid.UUID
	Name       string
	Prefix     string
	LastUsedAt sql.NullTime
	CreatedAt  time.Time
}

func (q *Queries) ListAPITokens(ctx context.Context, workspaceID uuid.UUID) ([]ListAPITokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensRow
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
	return err
}
