// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tokens.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, workspace_id FROM api_tokens WHERE token_hash = $1
`

type GetAPITokenByHashRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(&i.ID, &i.WorkspaceID)
	return i, err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
	return err
}
