// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, plan, billing_email, currency
FROM workspaces WHERE id = $1
`

type GetWorkspaceRow struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	Plan         string
	BillingEmail sql.NullString
	Currency     string
}

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (GetWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i GetWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.BillingEmail,
		&i.Currency,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET
  name          = COALESCE($2, name),
  billing_email = COALESCE($3, billing_email),
  currency      = COALESCE($4, currency)
WHERE id = $1
RETURNING id, name, slug, plan, billing_email, currency
`

type UpdateWorkspaceParams struct {
	ID           uuid.UUID
	Name         string
	BillingEmail sql.NullString
	Currency     string
}

type UpdateWorkspaceRow struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	Plan         string
	BillingEmail sql.NullString
	Currency     string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (UpdateWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.BillingEmail,
		arg.Currency,
	)
	var i UpdateWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.BillingEmail,
		&i.Currency,
	)
	return i, err
}
